package de.schildbach.wallet.livedata

enum class RegistrationStep {
    NOT_REGISTERED,
    UPGRADING_WALLET,
    CREDIT_FUNDING_TX_CREATING,
    CREDIT_FUNDING_TX_SENDING,
    CREDIT_FUNDING_TX_SENT,
    CREDIT_FUNDING_TX_CONFIRMED,
    IDENTITY_REGISTERING,
    IDENTITY_REGISTERED,
    PREORDER_REGISTERING,
    PREORDER_REGISTERED,
    USERNAME_REGISTERING,
    USERNAME_REGISTERED
}